version: '2.1'

services:
  app:
    container_name: monitoring_app
    build: .
    networks:
      - monitoring
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    env_file: .env

  db:
    container_name: monitoring_db
    image: influxdb:1.8
    networks:
      - monitoring
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: 'true'
    env_file: .env
    volumes:
      - './influxdb:/var/lib/influxdb'
    healthcheck:
      test: 'curl -f http://localhost:8086/ping'
      interval: 3s
      timeout: 10s
      retries: 5

networks:
  monitoring:
