version: '2.1'

services:
  app:
    container_name: monitoring_app
    build: .
    networks:
      - monitoring
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_NAME: monitoring
      DATABASE_HOST: monitoring_db
      DATABASE_PORT: 8086
      HOST_POOL_URL: https://online.stationf.co/tests/ip.json
      API_PORT: 8080

  db:
    container_name: monitoring_db
    image: influxdb:1.8
    networks:
      - monitoring
    volumes:
      - './influxdb:/var/lib/influxdb'
    healthcheck:
      test: 'curl -f http://localhost:8085/ping'
      interval: 3s
      timeout: 10s
      retries: 5

networks:
  monitoring:
